spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.springnext.demo: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extact: TRACE